### ISSUE TITLE
torch.jit.frontend.NotSupportedError

### ISSUE THREAD

**Issue by deepdad** [AaltoVision/DGC-Net#3]
Is it Python2 or pytorch version specific?

python3 eval.py --image-data-path ~/hpatches-sequences-release
Traceback (most recent call last):
  File "eval.py", line 8, in <module>
    import torchvision.transforms as transforms
  File "/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/rpn.py", line 8, in <module>
    from . import _utils as det_utils
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/_utils.py", line 74, in <module>
    @torch.jit.script
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 364, in script
    graph = _script_graph(fn, _frames_up=_frames_up + 1)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 359, in _script_graph
    ast = get_jit_ast(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 132, in get_jit_ast
    return build_def(SourceRangeFactory(source), py_ast.body[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 151, in build_def
    build_stmts(ctx, body))
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 123, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 123, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 205, in build_Assign
    rhs = build_expr(ctx, stmt.value)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 314, in build_Call
    func = build_expr(ctx, expr.func)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 300, in build_Attribute
    value = build_expr(ctx, expr.value)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 422, in build_Subscript
    raise NotSupportedError(base.range(), "slicing multiple dimensions at the same time isn't supported yet")
torch.jit.frontend.NotSupportedError: slicing multiple dimensions at the same time isn't supported yet
        proposals (Tensor): boxes to be encoded
    """

    # perform some unpacking to make it JIT-fusion friendly
    wx = weights[0]
    wy = weights[1]
    ww = weights[2]
    wh = weights[3]

    proposals_x1 = proposals[:, 0].unsqueeze(1)
                   ~~~~~~~~~ <--- HERE
    proposals_y1 = proposals[:, 1].unsqueeze(1)
    proposals_x2 = proposals[:, 2].unsqueeze(1)
    proposals_y2 = proposals[:, 3].unsqueeze(1)

    reference_boxes_x1 = reference_boxes[:, 0].unsqueeze(1)
    reference_boxes_y1 = reference_boxes[:, 1].unsqueeze(1)
    reference_boxes_x2 = reference_boxes[:, 2].unsqueeze(1)
    reference_boxes_y2 = reference_boxes[:, 3].unsqueeze(1)

**Comment by imelekhov** [comment]
Hi,
We do not support `python2` as clearly mentioned in the installation procedure.

**Comment by LorenzoFramba** [comment]
I'm getting the same error on Colab for a CNN problem in Semantic Segmentation. Have you solved it yet?

**Comment by koala992** [comment]
i use python 3.6 and have the same error. have you solved it?
