### ISSUE TITLE
0%

### ISSUE THREAD

**Issue by deepdad** [AaltoVision/DGC-Net#5]
DGC-Net$ python3.7 eval.py --image-data-path ~/hpatches-sequences-release
  0%|                                                                 | 0/59 [00:00<?, ?it/s]torch.Size([1, 225, 15, 15])

It outputs a torch.size with 0% progress bar by running the first test from the Readme. Probably not quite right, is it? It reported

GC-Net$ python3.7 eval.py --image-data-path ~/hpatches-sequences-release
  0%|                                                                 | 0/59 [00:00<?, ?it/s]torch.Size([1, 225, 15, 15])
Traceback (most recent call last):
  File "eval.py", line 93, in <module>
    device)
  File "/home/ubuntu/sticker_detection/DGC-Net/utils/evaluate.py", line 61, in calculate_epe_hpatches
    estimates_grid, estimates_mask = net(source_img, target_img)
  File "/home/ubuntu/anaconda3/envs/match/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/match/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/match/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/sticker_detection/DGC-Net/model/net.py", line 68, in forward
    sys.exit()
NameError: name 'sys' is not defined

before, which I fixed by importing sys obviously.

**Comment by imelekhov** [comment]
I think it's been fixed now. Thanks.
